spring:
  thymeleaf:
    cache: false
  application:
    name: service-views

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    should-unregister-on-shutdown: false
    decoder-name: JacksonJson
    fetch-registry: true
    register-with-eureka: true